### PR TITLE
External properties file timeout is treated as string and throws NFE.

### PR DESCRIPTION
**Pull request by ctoestreich**

### CODE REVIEW

**Comment by tednaleid** [comment]
Thanks Christian, I'll get this released tonight.

**Comment by ctoestreich** [comment]
Thanks!  Any work towards grails 3?

**Comment by tednaleid** [comment]
After applying this patch, I'm getting the following error when running all tests:

```
| Compiling 23 source files.....
| Error Fatal error running tests: No signature of method: groovy.util.ConfigObject.isInteger() is applicable for argument types: () values: [] (Use --stacktrace to see the full trace)
```

Is there a reason that you stripped out the test to check to see if it was a `String` class?

**Comment by tednaleid** [comment]
Made a [tweak to the property loading that I think accomplishes the same thing](https://github.com/grails-plugins/grails-redis/commit/dd418ee281a0a89604acd9ada76af12b1131996c).  Let me know if I missed a nuance in what you were doing, otherwise I'll release this shortly.

Groovy `ConfigObject`s are weird half-assed maps that don't behave like normal maps do, so the values that they return aren't falsy like they should be.  Have to use `isSet` to check if a value is actually set.

**Comment by ctoestreich** [comment]
I checked the code inline.  Passed the initial check for "", "foo" and "6379".  Could do a string first check, but seemed like isinteger did test.

**Comment by ctoestreich** [comment]
Your code looks good.

**Comment by tednaleid** [comment]
pushed out as 1.4.2, thanks again.

Regarding grails 3.  I haven't done anything for the redis plugin yet.  Have been talking with another dev about getting build-test-data, which is used by more people, upgraded first, but once that happens, redis will be the next one I'll upgrade.

**Pull request merged**
