### PR TITLE
Updating build.gradle

### PR DESCRIPTION
**Pull request by ctoestreich**
Adding new version for name change based on Bobby's blog post http://blog.agileorbit.com/2015/10/07/Publishing-Grails-3-Plugins.html

### CODE REVIEW

**Comment by ctoestreich** [comment]
@tednaleid Sorry buddy, sent off a couple pull requests as the last one was incomplete to meet @bobbywarner blog.

**Comment by ctoestreich** [comment]
Also when changing this repo to the corrected name there is technically a new artifact now.  If you rename your bintray repo from org.grails.plugins:redis to just redis, this should update downstream and this wil publish into there and @bobbywarner script will pick up name change.

Before publishing, delete the `redis` one.  Rename the other to just redis.  Then publish.  That will correct this.

screen shot 2016-02-11 at 9 47 30 am

**Comment by ctoestreich** [comment]
screen shot 2016-02-11 at 9 49 16 am
screen shot 2016-02-11 at 9 49 09 am

**Comment by tednaleid** [comment]
@ctoestreich sorry about the delay getting to reviewing/merging these.  my days aren't really related to grails at all anymore.  do you have any interest in taking over maintenance of this plugin so that I'm not a blocker for your changes anymore?  It's complicated slightly because this repo is part of the `grails-plugins` repo so I'm not sure I can just reassign ownership.  You might need to talk to the grails team to ask about taking it over if you're interested.

**Comment by ctoestreich** [comment]
@tednaleid Maybe the best way is to get me access to the grails-redis repo via an admin.

**Comment by ctoestreich** [comment]
@tednaleid I think the real issue here is that your personal bintray is linked to this plugin downstream

**Comment by tednaleid** [comment]
@ctoestreich Graeme said on twitter that he has sent you an invite to the group.  I also mentioned how the publishing of jars on bintray needs to move off my personal account.  Let me know if you need anything else to make it so you can do the releases without having me holding things up.

**Pull request merged**
