### PR TITLE
Exclude web-app folder from plugin.

### PR DESCRIPTION
**Pull request by kevana**
Ran into some issues with assets from the redis plugin overriding assets from other plugins, I think it can all be excluded.

screen shot 2015-05-04 at 11 52 42 am

### CODE REVIEW

**Comment by tednaleid** [comment]
Yep, that should have been excluded, thanks for the PR!

**Comment by tednaleid** [comment]
published as [2.0.1](https://bintray.com/tednaleid/grails-plugins/org.grails.plugins%3Agrails-redis/2.0.1/view)

**Comment by kevana** [comment]
Thanks, do I need to do anything special to backport to 1.6.4? I branched off of the tag but when I [compare](https://github.com/grails-plugins/grails-redis/compare/1.6.4...kevana:exclude-web-app) there's no button to open a PR.

**Comment by kevana** [comment]
I think there needs to be a branch in this repo at tag 1.6.4 for me to PR onto it.

**Comment by tednaleid** [comment]
Created a `grails_2` branch from 1.6.4.

**Pull request merged**
